name: CI/CD - Build and Deploy PROTFOLIO to S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --force

    - name: Build the app
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --force

    - name: Build the app
      run: npm run build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --follow-symlinks --delete


      env:
        AWS_S3_BUCKET: ${{ secrets.BUCKET }}
        AWS_REGION: ${{ secrets.REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ACL: 'public-read'
        DELETE: 'true'
        SOURCE_DIR: './build' 
